version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.159.1/hugo_extended_0.159.1_Linux-64bit.tar.gz -O hugo.tar.gz
      - tar -xzf hugo.tar.gz
      - sudo mv hugo /usr/local/bin/
      - rm -f hugo.tar.gz LICENSE README.md
      - hugo version

  build:
    commands:
      - cd my-hugo-site && hugo --gc --minify

  post_build:
    commands:
      - aws s3 sync my-hugo-site/public/ s3://cld4300-kyle-osborne-hugo --delete
