version: 0.2

phases:
  install:
    commands:
      - wget -q https://github.com/gohugoio/hugo/releases/download/v0.159.1/hugo_extended_0.159.1_Linux-64bit.tar.gz -O hugo.tar.gz
      - tar -xzf hugo.tar.gz
      - sudo mv hugo /usr/local/bin/
      - rm -f hugo.tar.gz LICENSE README.md
      - hugo version

  build:
    commands:
      - cd my-hugo-site
      - hugo --gc --minify
      - aws s3 sync public/ s3://cld4300-kyle-osborne-hugo --delete
